### ISSUE TITLE
[1.17.1] Class not found error on launch

### ISSUE THREAD

**Issue by kwpugh** [TheCharlsen/CharlsensIdeas#1] opened 2021-09-12 18:24 UTC
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 9/12/21, 1:16 PM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'charlsensideas'!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:33)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:34)
	at net.minecraft.class_310.<init>(class_310.java:457)
	at net.minecraft.client.main.Main.main(Main.java:179)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.NoClassDefFoundError: io/github/waterpicker/openworlds/renderer/SkyRenderer
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:466)
	at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.EntrypointStorage$NewEntry.lambda$getOrCreate$0(EntrypointStorage.java:106)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1224)
	at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:104)
	at net.fabricmc.loader.EntrypointStorage.lambda$getEntrypointContainers$1(EntrypointStorage.java:191)
	at net.fabricmc.loader.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:37)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 19 more
Caused by: java.lang.ClassNotFoundException: io.github.waterpicker.openworlds.renderer.SkyRenderer
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:175)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	... 28 more

**Comment by TheCharlsen** [comment] 2021-09-12 19:17
Gonna be fixed tomorrow

**Comment by TheCharlsen** [comment] 2021-09-12 19:20
Can i ask how it happened, so what version and what did you do?

**Comment by kwpugh** [comment] 2021-09-12 20:03
just tried to run charlsens-ideas-Beta+0.2.0 in my 1.17.1 modpack

**Comment by kwpugh** [comment] 2021-09-12 20:05
figured it was a missing dependency but nothing shows on CurseForge page and can find the referenced mod either.

**Comment by kwpugh** [comment] 2021-09-12 20:20
I found the sources to OpenWorlds, may update it to latest 1.17.1 and play around.

**Comment by TheCharlsen** [comment] 2021-09-12 20:21
So the report says its caused by OpenWorlds. I havent updated it in a  while maybe that fixes it. The only thing is the mod runs fine when i play it

**Comment by TheCharlsen** [comment] 2021-09-12 20:22
Yup i am gonna do that

**Comment by kwpugh** [comment] 2021-09-12 20:41
Ah.  Is OpenWorlds now longer being updated?

**Comment by TheCharlsen** [comment] 2021-09-12 20:42
Yeah idk i am searching for a new version but there might not be one

**Comment by TheCharlsen** [comment] 2021-09-12 20:44
Hmm i have to do some tests

**Comment by kwpugh** [comment] 2021-09-12 20:47
Yeah, I got it working, looks like some things need work.  I was just curious what was in your mod, lol.

![Screen Shot 2021-09-12 at 3 46 38 PM](https://user-images.githubusercontent.com/8809210/133002315-89a3942c-2553-46e8-bc11-34a29415b9ba.png)

**Comment by TheCharlsen** [comment] 2021-09-12 20:49
Yeah it still needs work. The purple black blocks are just temporary. And all the woods blocks are also still coming soon

**Comment by TheCharlsen** [comment] 2021-09-12 20:50
And recipes

**Comment by kwpugh** [comment] 2021-09-12 20:50
I'm a modded as well, I feel your pain.

**Comment by TheCharlsen** [comment] 2021-09-12 20:50
😂 btw how did you fix it?

**Comment by kwpugh** [comment] 2021-09-12 20:53
Nice worldgen though

![Screen Shot 2021-09-12 at 3 52 34 PM](https://user-images.githubusercontent.com/8809210/133002452-8956a607-135d-4a23-b61e-d2c5ddebd0ad.png)

just need to fix a few of the mixins

**Comment by TheCharlsen** [comment] 2021-09-12 20:55
Thanks. But what do you mean with fixing mixins. For the Open worlds bug or in my mod. Cause i wanna know which?

**Comment by kwpugh** [comment] 2021-09-12 20:59
I'm not working with your sources.  I updated OpenWorlds to latest build of 1.17.1, updated gradle, and then made some fixes to one of OpenWorlds mixins that was throwing errors:  https://gist.github.com/kwpugh/13b454afb7c0c72b4043765a5404c9b0

Then I built it and ran it from the launcher with your latest release from Curseforge

**Comment by kwpugh** [comment] 2021-09-12 21:00
The method signature for renderSky had changed in latest.

**Comment by TheCharlsen** [comment] 2021-09-12 21:03
Ahh but i cant upgrade openworlds from the dependencies in my mod right now or am i wrong?

**Comment by kwpugh** [comment] 2021-09-12 21:07
this?  	modImplementation("com.github.Mysticpasta1:OpenWorlds:cce9fed") {
		exclude module: "fabric-api"

you would have to include yourself since the GitHub is not updated.

**Comment by kwpugh** [comment] 2021-09-12 21:08
you could jar-in-jar or publish to a local maven and compile into your mod

**Comment by TheCharlsen** [comment] 2021-09-12 21:09
Oh shit no idea how to do that, i never really worked with maven

**Comment by kwpugh** [comment] 2021-09-12 21:10
I'm pulling a copy of your sources into my dev to take a look

**Comment by TheCharlsen** [comment] 2021-09-12 21:11
Ok

**Comment by kwpugh** [comment] 2021-09-12 21:35
After some playing around, I got it working without the external OpenWorlds dependency.   I published the updated version to a local maven on my computer, then updated the build.gradle in your mod

	include "io.github.waterpicker:OpenWorlds-master:1.1.0"
	modImplementation "io.github.waterpicker:OpenWorlds-master:1.1.0"

and added to the repositories section

mavenLocal()

then did a gradle --refresh-dependencies and then a gradle build.

I was then able to run the jar by itself

**Comment by kwpugh** [comment] 2021-09-12 21:36
the include statement above packages a copy from my local maven into the built mod jar at build time

**Comment by TheCharlsen** [comment] 2021-09-12 21:38
So what does that mean for me? How would i do that what you just did to fix that?

**Comment by kwpugh** [comment] 2021-09-12 21:52
did  you already update a copy of OpenWorlds?

**Comment by TheCharlsen** [comment] 2021-09-12 21:52
nope

**Comment by kwpugh** [comment] 2021-09-12 21:56
well that would be step 1  so you have your own working version.

**Comment by kwpugh** [comment] 2021-09-12 21:57
[openworlds-1.1.0-sources-dev.zip](https://github.com/TheCharlsen/CharlsensIdeas/files/7150354/openworlds-1.1.0-sources-dev.zip)

**Comment by kwpugh** [comment] 2021-09-12 21:59
bring it into your dev environment

**Comment by TheCharlsen** [comment] 2021-09-12 22:00
Yeah i am gonna do that right now my internet is really slow so its gonna take s while to download

**Comment by kwpugh** [comment] 2021-09-12 22:04
when  you get it working correctly, then publish it  to a local maven with: 

gradle publishToMavenLocal

**Comment by TheCharlsen** [comment] 2021-09-12 22:08
You send it without any properties or gradle so its just all red
And the command gradle could not be found

**Comment by kwpugh** [comment] 2021-09-12 22:08
that  will publish to  the location your IDE has for a local  maven.   For me it is under /m2/repository in my user folder

**Comment by kwpugh** [comment] 2021-09-12 22:09
oh sorry, hang on.

**Comment by kwpugh** [comment] 2021-09-12 22:10
[Archive.zip](https://github.com/TheCharlsen/CharlsensIdeas/files/7150372/Archive.zip)

**Comment by TheCharlsen** [comment] 2021-09-12 22:13
Ok no errors

**Comment by kwpugh** [comment] 2021-09-12 22:18
that's good.   Did you publish to local maven?

**Comment by kwpugh** [comment] 2021-09-12 22:19
it might be easier if you come over to my discord for the  chatting.  Up  to you.


https://discord.gg/xUbgfnsd

**Comment by TheCharlsen** [comment] 2021-09-12 22:19
Ok

**Comment by kwpugh** [comment] 2021-09-12 22:20
come to #mod-development channel

**Comment by TheCharlsen** [comment] 2021-09-12 22:20
ok

**Comment by TheCharlsen** [comment] 2021-09-12 23:29
Fixed in version beta 0.2.1

**Closed as completed** 2021-09-12 23:28 UTC
